!!- if .Values.serviceAccount.create -??
apiVersion: v1
kind: ServiceAccount
metadata:
  name: !! include "inventario.serviceAccountName" . ??
  labels:
    !!- include "inventario.labels" . | nindent 4 ??
  !!- with .Values.serviceAccount.annotations ??
  annotations:
    !!- toYaml . | nindent 4 ??
  !!- end ??
!!- end ??
